Refactor MasterButton
janeliasz/wearit pull request #24
Opened 2022-12-10 21:30 UTC by janeliasz

2022-12-12 16:51 UTC, michal-sternik commented on app/src/main/java/com/example/wearit/ui/WardrobeScreen.kt
>                      MasterButton(
mieliśmy dodać ikonkę "powrót" jeśli chcieliśmy odwrócić efekt usunięcia tła. aktualnie po usunięciu tła na przycisku wciąż widnieją nożyczki.
myślę, że ta ikonka będzie git: https://www.flaticon.com/free-icon/undo-arrow_25249?related_id=25249

2022-12-12 16:56 UTC, michal-sternik requested changes

2022-12-12 16:56 UTC, michal-sternik commented on app/src/main/java/com/example/wearit/ui/WardrobeScreen.kt
> +        horizontalArrangement = Arrangement.spacedBy(10.dp)
wcześniej chyba było Arrangement.SpaceEvenly. czy ta opcja spacedBy rzeczywiście będzie lepsza? (jeśli chodzi o działanie na innych urządzeniach - operujemy tu na tych jednostkach dp gdzie przy Arrangement.SpaceEvenly mieliśmy dopasowanie do każdego urządzenia)

2022-12-12 16:56 UTC, michal-sternik commented on app/src/main/res/drawable/ic_baseline_content_cut_24.xml
> +</vector>
to jest ta ikonka nożyczek tak? nie lepiej byłoby ją wgrać po prostu jako jakiś png? tak samo w przypadku ikonki zapisu

2022-12-12 16:56 UTC, michal-sternik commented on app/src/main/java/com/example/wearit/ui/WardrobeScreen.kt
>                      )
mieliśmy dodać ikonkę "powrót" jeśli chcieliśmy odwrócić efekt usunięcia tła. aktualnie po usunięciu tła na przycisku wciąż widnieją nożyczki.
myślę, że ta ikonka będzie git: https://www.flaticon.com/free-icon/undo-arrow_25249?related_id=25249

2022-12-14 17:17 UTC, janeliasz commented on app/src/main/java/com/example/wearit/ui/WardrobeScreen.kt
> +        horizontalArrangement = Arrangement.spacedBy(10.dp)
Tak, ale wcześniej przyciski miały z góry ustalony padding, a teraz go nie mają. Poza tym, przyciski mają fillMaxWidth().weight(1f), więc teraz SpaceEvenly nic nie zmienia i żeby miedzy tymi przyciskami był jakiś odstęp to musiałem użyć spacedBy() i podać jakąś wartość. Próbowałem jeszcze jakoś inaczej to rozwiązać żeby to było bardziej elastyczne, ale nie znalazłem żadnego sensownego i działającego rozwiązania

2022-12-14 17:50 UTC, michal-sternik commented on app/src/main/java/com/example/wearit/ui/WardrobeScreen.kt
> +        horizontalArrangement = Arrangement.spacedBy(10.dp)
Oki rozumiem

2022-12-14 17:51 UTC, michal-sternik approved these changes

2022-12-14 19:16 UTC, merged