wardrobe category change and button to draw
janeliasz/wearit pull request #4
Opened 2022-11-09 21:46 UTC by michal-sternik

mozecie dac znac czy to w taki sposob miala ta nawigacja pomiedzy kategoriami byc zrobiona; nie wiem jeszcze jak ogarnąć to, by  guziki miały osobne fonty(w typography (plik type.kt) mozna ustalić tylko jeden styl fonta dla wszystkich przycisków i słabo to wygląda bo wszystkie przyciski mają ten sam font size itd

2022-11-10 07:07 UTC, janeliasz requested changes

2022-11-10 07:07 UTC, janeliasz commented on app/src/main/java/com/example/wearit/WearItApp.kt
> +                goToHeadGears = {viewModel.goToCategory(Category.Headgear)},
Nie powinniśmy przekazywać osobnego wywołania funkcji goToCategory dla każdej kategorii, tylko przekazać jedną lambdę, która będzie wywoływać goToCategory z odpowiednim argumentem. Mogło by to na przykład wyglądać tak: onCategoryChange = { viewModel.goToCategory(it) }

2022-11-10 07:07 UTC, janeliasz commented on app/src/main/java/com/example/wearit/model/AppUiState.kt
> +    var currentCategory: Category = Category.Headgear
Tu powinno być val

2022-11-10 07:07 UTC, janeliasz commented on app/src/main/java/com/example/wearit/ui/AppViewModel.kt
> +        _uiState.value = AppUiState(category)
Nie możemy zmieniać stanu w ten sposób. Zamiast tego powinniśmy użyć metody update obiektu _uiState: 
_uiState.update { currentState -> 
  currentState.copy(
    currentCategory = category
  )
}

2022-11-10 07:07 UTC, janeliasz commented on app/src/main/java/com/example/wearit/ui/WardrobeScreen.kt
> +    Column {
Tutaj bym proponował LazyColumn zamiast Column i tam wykorzystać funkcję items, to zajmie to dużo mniej linii

2022-11-10 11:48 UTC, michal-sternik commented
mam nadzieję, że dobrze zupdateowalem tego pull requesta, udało mi się poprawić wszystko

2022-11-10 20:56 UTC, janeliasz commented on app/src/main/java/com/example/wearit/ui/WardrobeScreen.kt
> +        ExtendedFloatingActionButton(
Potrzebujemy stworzyć osobny komponent Button, którego będziemy używać w całym projekcie. A żeby zrobić tego Buttona no to najpierw musimy ogarnąć cały Theme w projekcie. Ale to wszystko już wychodzi poza scope twojego pull requesta, dlatego póki co wywal ten przycisk DRAW, który jest teraz i wrzuć tu po prostu najzwyklejszy Button, bez żadnego stylowania (żadnych fontów, paddingow, modifierow itd.), byle tylko działał po naciśnięciu (pamiętaj żeby usunąć niepotrzebną zmienną fonts). A jak już będziemy mieć nasz własny customowy button to go tutaj użyjemy

2022-11-11 12:17 UTC, janeliasz approved these changes

2022-11-12 09:54 UTC, merged